package com.luqili.db.dao.base;

import com.luqili.db.beans.base.Img;

public interface ImgMapper extends BaseMapper<Img> {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table base.lu_img
	 * @mbggenerated
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table base.lu_img
	 * @mbggenerated
	 */
	int insert(Img record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table base.lu_img
	 * @mbggenerated
	 */
	int insertSelective(Img record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table base.lu_img
	 * @mbggenerated
	 */
	Img selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table base.lu_img
	 * @mbggenerated
	 */
	int updateByPrimaryKeySelective(Img record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table base.lu_img
	 * @mbggenerated
	 */
	int updateByPrimaryKey(Img record);
}