package com.luqili.db.dao.base;

import org.apache.ibatis.annotations.ResultMap;
import org.apache.ibatis.annotations.Select;

import com.luqili.db.beans.base.User;

public interface UserMapper extends BaseMapper<User> {
    /**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table base.lu_user
	 * @mbggenerated
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table base.lu_user
	 * @mbggenerated
	 */
	int insert(User record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table base.lu_user
	 * @mbggenerated
	 */
	int insertSelective(User record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table base.lu_user
	 * @mbggenerated
	 */
	User selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table base.lu_user
	 * @mbggenerated
	 */
	int updateByPrimaryKeySelective(User record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table base.lu_user
	 * @mbggenerated
	 */
	int updateByPrimaryKey(User record);

	@ResultMap(value="BaseResultMap")
    @Select("select * from base.lu_user where username=#{userName,jdbcType=VARCHAR}")
    User selectByUserName(String userName);
}