package com.luqili.db.dao.base;

import com.luqili.db.beans.base.UserDetail;

public interface UserDetailMapper  extends BaseMapper<UserDetail>{

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table base.lu_user_detail
	 * @mbggenerated
	 */
	int deleteByPrimaryKey(Integer userId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table base.lu_user_detail
	 * @mbggenerated
	 */
	int insert(UserDetail record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table base.lu_user_detail
	 * @mbggenerated
	 */
	int insertSelective(UserDetail record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table base.lu_user_detail
	 * @mbggenerated
	 */
	UserDetail selectByPrimaryKey(Integer userId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table base.lu_user_detail
	 * @mbggenerated
	 */
	int updateByPrimaryKeySelective(UserDetail record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table base.lu_user_detail
	 * @mbggenerated
	 */
	int updateByPrimaryKey(UserDetail record);
}