package com.luqili.db.beans.base;

import java.util.Date;

public class Img {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column base.lu_img.id
	 * @mbggenerated
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column base.lu_img.add_time
	 * @mbggenerated
	 */
	private Date addTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column base.lu_img.status
	 * @mbggenerated
	 */
	private Integer status;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column base.lu_img.img_type
	 * @mbggenerated
	 */
	private Integer imgType;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column base.lu_img.add_user_id
	 * @mbggenerated
	 */
	private Integer addUserId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column base.lu_img.name
	 * @mbggenerated
	 */
	private String name;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column base.lu_img.filename
	 * @mbggenerated
	 */
	private String filename;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column base.lu_img.ext
	 * @mbggenerated
	 */
	private String ext;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column base.lu_img.path
	 * @mbggenerated
	 */
	private String path;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column base.lu_img.url
	 * @mbggenerated
	 */
	private String url;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column base.lu_img.size
	 * @mbggenerated
	 */
	private Long size;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column base.lu_img.id
	 * @return  the value of base.lu_img.id
	 * @mbggenerated
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column base.lu_img.id
	 * @param id  the value for base.lu_img.id
	 * @mbggenerated
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column base.lu_img.add_time
	 * @return  the value of base.lu_img.add_time
	 * @mbggenerated
	 */
	public Date getAddTime() {
		return addTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column base.lu_img.add_time
	 * @param addTime  the value for base.lu_img.add_time
	 * @mbggenerated
	 */
	public void setAddTime(Date addTime) {
		this.addTime = addTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column base.lu_img.status
	 * @return  the value of base.lu_img.status
	 * @mbggenerated
	 */
	public Integer getStatus() {
		return status;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column base.lu_img.status
	 * @param status  the value for base.lu_img.status
	 * @mbggenerated
	 */
	public void setStatus(Integer status) {
		this.status = status;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column base.lu_img.img_type
	 * @return  the value of base.lu_img.img_type
	 * @mbggenerated
	 */
	public Integer getImgType() {
		return imgType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column base.lu_img.img_type
	 * @param imgType  the value for base.lu_img.img_type
	 * @mbggenerated
	 */
	public void setImgType(Integer imgType) {
		this.imgType = imgType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column base.lu_img.add_user_id
	 * @return  the value of base.lu_img.add_user_id
	 * @mbggenerated
	 */
	public Integer getAddUserId() {
		return addUserId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column base.lu_img.add_user_id
	 * @param addUserId  the value for base.lu_img.add_user_id
	 * @mbggenerated
	 */
	public void setAddUserId(Integer addUserId) {
		this.addUserId = addUserId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column base.lu_img.name
	 * @return  the value of base.lu_img.name
	 * @mbggenerated
	 */
	public String getName() {
		return name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column base.lu_img.name
	 * @param name  the value for base.lu_img.name
	 * @mbggenerated
	 */
	public void setName(String name) {
		this.name = name == null ? null : name.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column base.lu_img.filename
	 * @return  the value of base.lu_img.filename
	 * @mbggenerated
	 */
	public String getFilename() {
		return filename;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column base.lu_img.filename
	 * @param filename  the value for base.lu_img.filename
	 * @mbggenerated
	 */
	public void setFilename(String filename) {
		this.filename = filename == null ? null : filename.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column base.lu_img.ext
	 * @return  the value of base.lu_img.ext
	 * @mbggenerated
	 */
	public String getExt() {
		return ext;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column base.lu_img.ext
	 * @param ext  the value for base.lu_img.ext
	 * @mbggenerated
	 */
	public void setExt(String ext) {
		this.ext = ext == null ? null : ext.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column base.lu_img.path
	 * @return  the value of base.lu_img.path
	 * @mbggenerated
	 */
	public String getPath() {
		return path;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column base.lu_img.path
	 * @param path  the value for base.lu_img.path
	 * @mbggenerated
	 */
	public void setPath(String path) {
		this.path = path == null ? null : path.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column base.lu_img.url
	 * @return  the value of base.lu_img.url
	 * @mbggenerated
	 */
	public String getUrl() {
		return url;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column base.lu_img.url
	 * @param url  the value for base.lu_img.url
	 * @mbggenerated
	 */
	public void setUrl(String url) {
		this.url = url == null ? null : url.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column base.lu_img.size
	 * @return  the value of base.lu_img.size
	 * @mbggenerated
	 */
	public Long getSize() {
		return size;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column base.lu_img.size
	 * @param size  the value for base.lu_img.size
	 * @mbggenerated
	 */
	public void setSize(Long size) {
		this.size = size;
	}
}