package com.luqili.db.beans.base;

public class UserDetail {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column base.lu_user_detail.user_id
	 * @mbggenerated
	 */
	private Integer userId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column base.lu_user_detail.name
	 * @mbggenerated
	 */
	private String name;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column base.lu_user_detail.sex
	 * @mbggenerated
	 */
	private Integer sex;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column base.lu_user_detail.phone
	 * @mbggenerated
	 */
	private String phone;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column base.lu_user_detail.tel
	 * @mbggenerated
	 */
	private String tel;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column base.lu_user_detail.qq
	 * @mbggenerated
	 */
	private String qq;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column base.lu_user_detail.idcard
	 * @mbggenerated
	 */
	private String idcard;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column base.lu_user_detail.address
	 * @mbggenerated
	 */
	private String address;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column base.lu_user_detail.head_img_id
	 * @mbggenerated
	 */
	private Integer headImgId;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column base.lu_user_detail.user_id
	 * @return  the value of base.lu_user_detail.user_id
	 * @mbggenerated
	 */
	public Integer getUserId() {
		return userId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column base.lu_user_detail.user_id
	 * @param userId  the value for base.lu_user_detail.user_id
	 * @mbggenerated
	 */
	public void setUserId(Integer userId) {
		this.userId = userId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column base.lu_user_detail.name
	 * @return  the value of base.lu_user_detail.name
	 * @mbggenerated
	 */
	public String getName() {
		return name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column base.lu_user_detail.name
	 * @param name  the value for base.lu_user_detail.name
	 * @mbggenerated
	 */
	public void setName(String name) {
		this.name = name == null ? null : name.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column base.lu_user_detail.sex
	 * @return  the value of base.lu_user_detail.sex
	 * @mbggenerated
	 */
	public Integer getSex() {
		return sex;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column base.lu_user_detail.sex
	 * @param sex  the value for base.lu_user_detail.sex
	 * @mbggenerated
	 */
	public void setSex(Integer sex) {
		this.sex = sex;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column base.lu_user_detail.phone
	 * @return  the value of base.lu_user_detail.phone
	 * @mbggenerated
	 */
	public String getPhone() {
		return phone;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column base.lu_user_detail.phone
	 * @param phone  the value for base.lu_user_detail.phone
	 * @mbggenerated
	 */
	public void setPhone(String phone) {
		this.phone = phone == null ? null : phone.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column base.lu_user_detail.tel
	 * @return  the value of base.lu_user_detail.tel
	 * @mbggenerated
	 */
	public String getTel() {
		return tel;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column base.lu_user_detail.tel
	 * @param tel  the value for base.lu_user_detail.tel
	 * @mbggenerated
	 */
	public void setTel(String tel) {
		this.tel = tel == null ? null : tel.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column base.lu_user_detail.qq
	 * @return  the value of base.lu_user_detail.qq
	 * @mbggenerated
	 */
	public String getQq() {
		return qq;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column base.lu_user_detail.qq
	 * @param qq  the value for base.lu_user_detail.qq
	 * @mbggenerated
	 */
	public void setQq(String qq) {
		this.qq = qq == null ? null : qq.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column base.lu_user_detail.idcard
	 * @return  the value of base.lu_user_detail.idcard
	 * @mbggenerated
	 */
	public String getIdcard() {
		return idcard;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column base.lu_user_detail.idcard
	 * @param idcard  the value for base.lu_user_detail.idcard
	 * @mbggenerated
	 */
	public void setIdcard(String idcard) {
		this.idcard = idcard == null ? null : idcard.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column base.lu_user_detail.address
	 * @return  the value of base.lu_user_detail.address
	 * @mbggenerated
	 */
	public String getAddress() {
		return address;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column base.lu_user_detail.address
	 * @param address  the value for base.lu_user_detail.address
	 * @mbggenerated
	 */
	public void setAddress(String address) {
		this.address = address == null ? null : address.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column base.lu_user_detail.head_img_id
	 * @return  the value of base.lu_user_detail.head_img_id
	 * @mbggenerated
	 */
	public Integer getHeadImgId() {
		return headImgId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column base.lu_user_detail.head_img_id
	 * @param headImgId  the value for base.lu_user_detail.head_img_id
	 * @mbggenerated
	 */
	public void setHeadImgId(Integer headImgId) {
		this.headImgId = headImgId;
	}
}